// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package logger

import (
	"github.com/geekswap/zenith/pkg/logger"
)

// Injectors from wire.go:

func ProvideLogger() logger.Logger {
	loggerLogger := logger.New()
	return loggerLogger
}
